### ISSUE TITLE
limiting plugins or languages fo precompile

### ISSUE THREAD

**Issue by mbaniasad** [tsechingho/ckeditor-rails#52]
is there a way to limit the number of languages and plugins to reduce precompilation time.
this takes a long on heroku and causes heroku compilation time out....

**Comment by JakeTheSnake3p0** [comment]
+1

**Comment by griebd** [comment]
@HunterMeyer, just changed from https://github.com/galetahub/ckeditor to this because the config you mentioned doesn't work there...
At least here, https://github.com/tsechingho/ckeditor-rails, there is some recent updates...

But my question to anyone: Is there a solution to limit languages and plugins in assets:precompile?

**Comment by tsechingho** [comment]
yes, there is way to have only limited languages and plugins while compiling assets.
it will add some configuration needs.

**Comment by USvER** [comment]
@tsechingho So is it fixed or not? having problems on heroku deployment too...

**Comment by HunterMeyer** [comment]
@USvER, I don't know if it's fixed. Doesn't seem like it. I use Heroku and AssetSync, maybe I can help. What problem are you having?

**Comment by USvER** [comment]
@HunterMeyer i've just disabled the ckeditor plugin and deployment is ok now... I can leave it disabled for now but this needs to fixed. All this language files is taking too much time to compile.

**Comment by bmishkin** [comment]
+1

**Comment by griebd** [comment]
@tsechingho you sad that there is a  way (or I misunderstood you?), is it documented somewhere? Could you explain how to do it? Some extra configuration is no problem at all...

**Comment by tsechingho** [comment]
It's not fixed yet. I will do some works for this issue this week and release a new version.

**Comment by tsechingho** [comment]
Hi, I release v4.4.8 of `ckeditor_rails` to support assets limitation today.

any suggestions are welcome, thanks.

**Comment by griebd** [comment]
That's great, thanks a lot for your work!!!! Really appreciated!!!!

**Comment by tsechingho** [comment]
@griebd there is a tip to have black list.

``` ruby
config.assets_plugins = Ckeditor::Rails.default_plugins - %w[about]
```
