### ISSUE TITLE
CKEdtiror assets not compiling (Rails 3.2.22 with 4.4.8)

### ISSUE THREAD

**Issue by balen** [tsechingho/ckeditor-rails#63]
When I deploy a rails 3.2.22 app using the ckeditor-rails gem everything was ok and the assets were compiled. But this no longer works with the latest release (4.4.8).

Test using
```
RAILS_ENV=development bundle exec rake assets:precompile
```

**Comment by tsechingho** [comment]
I create a brand new rails 3.2.22 project and apply ckeditor-rails gem.
It's all good for me.

![ckeditor_rails322](https://cloud.githubusercontent.com/assets/12554/8613106/929caa2e-270d-11e5-87ee-9b214582a16d.png)
