### ISSUE TITLE
Can't get some toolbar buttons to show with Rails 4.2.2

### ISSUE THREAD

**Issue by medBouzid** [tsechingho/ckeditor-rails#64]
I am customizing my toolbar like the following (my actual Rails version is 4.2.2, I tried this code in 4.2.0 and there is no problem)

    config.toolbar = [
        [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ],
        [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ],
        ['Font', 'FontSize','superlink'],
        ['TextColor', 'BGColor'],
        '/',
        [ 'Bold', 'Italic', 'Underline', 'Strike' ],
        [ 'Undo', 'Redo' ],
        ['Link', 'Unlink']
    ];    
But some buttons are missing like 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock',  'NumberedList', 'BulletedList' ...

**PS: Also without customizing the toolbar, those buttons don't show up !!**
Is this a bug ?

Thanks!

**Comment by tsechingho** [comment]
I have `app/assets/javascripts/ckeditor/config.js.coffee` like

``` 
CKEDITOR.editorConfig = (config) ->
  config.language = "zh"
  config.uiColor = "#AADC6E"
  config.toolbar = [
    [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ],
    [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ],
    ['Font', 'FontSize','superlink'],
    ['TextColor', 'BGColor'],
    '/',
    [ 'Bold', 'Italic', 'Underline', 'Strike' ],
    [ 'Undo', 'Redo' ],
    ['Link', 'Unlink'],
    ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', 'NumberedList', 'BulletedList']
  ]
```

and have a correct result like

![ckeditor_config](https://cloud.githubusercontent.com/assets/12554/8613215/fcc8e97a-270e-11e5-9561-173290d21ec7.png)
