### ISSUE TITLE
Cannot get rid of the BLOATWARE which is found to be pre-compiled in the assets of this gem.

### ISSUE THREAD

**Issue by netkgk** [tsechingho/ckeditor-rails#94]
The bloatware outputs a lot of garbage into the console:
```
[CKEDITOR] Error code: exportpdf-no-token-url.
```

Needless to say the `exportpdf` stuff was neither wanted nor included in the configuration, non-the-less it seems there's no way to get rid of it, except by manually editing pre-uglified assets included in the gem. The bloatware is initialized by [ckeditor/build-config.js](https://github.com/tsechingho/ckeditor-rails/blob/2f5a9a4d1881fba1916c5205817b53d288f1b53f/vendor/assets/javascripts/ckeditor/build-config.js#L73) which is getting unconditionally included in the final build overriding the plugin list from  initializer.

**Comment by tsechingho** [comment]
The `exportpdf` plugin could be removed, please edit your ckeditor config js, like `app/assets/javascripts/ckeditor/config.js.coffee`, as following:

``` coffee
CKEDITOR.editorConfig = (config) ->
  config.removePlugins = 'exportpdf'
  true
```

`exportpdf` is a [premium feature](https://ckeditor.com/cke4/addon/exportpdf) and default enabled in `full` package of ckeditor this gem used.

I will add related description in README later.
